### PR TITLE
Fixed missing export parameters for SPPM and Bidirecional light method

### PR DESCRIPTION
**Pull request by Micheus**
Note: Fixed missing export parameters for SPPM and Bidirecional. Thanks oort

_* JFYI, I'm not pushing this fix to the official Wings3D repository. I hope if you approving it you could make a PR to Dan's repository,_

### CODE REVIEW

**Comment by DavidBluecame** [comment]
Done! Thank you very much! :-)

**Comment by DavidBluecame** [comment]
Hi, Micheus. I cannot make a PR to Dan's repo because this repo is too far behind :-(

**Comment by DavidBluecame** [comment]
Perhaps we should make the YafaRay Wings3D plugin changes directly as PR to Dan's instead of using my repo?  Alternatively, perhaps we could just separate just the YafaRay plugin files into a different dedicated repo to avoid messing with the main Wings3D repo?

**Comment by Micheus** [comment]
Since you have pushing your code to Dan's repository, I always use the Dan's branch to make the changes before send to you. Usually that is not a problem. I just tried to make a PR myself using your repository and Github says it's OK to merge. (Interesting that I'm able to do that. I thought only you could do this)

YafarayV3-PR

Maybe you need to rebase your branch on the Dan's **maint** branch which is what I use to do in order to be sync with Dan's repository.

**Pull request merged**
